# Use C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# start with window 1 (instead of 0)
set -g base-index 1
# start with pane 1
set -g pane-base-index 1

set -g mode-keys vi
set -g status-keys vi

# reload source config file
bind -N "Reload the tmux configuration" r source-file ~/.config/tmux/tmux.conf

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# Use vim bindings in copy mode
set-window-option -g mode-keys vi
set -g set-clipboard off
bind-key -N "Start copy selection" -T copy-mode-vi v send-keys -X begin-selection
bind-key -N "End copy selection (and copy)" -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard > /dev/null"

# Change splits to more sensible defaults
unbind -
unbind /
bind-key -N "Split window vertically" - split-window -v -c "#{pane_current_path}"
bind-key -N "Split window horizontally" / split-window -h -c "#{pane_current_path}"

